"""SST test case generator.

Generates structural and unanswerable test cases from a live LadybugDB graph.
Ground truth is derived from graph structure — not LLM inference.
Query text is generated by a fast LLM as natural language variants of each
structural template.

Usage:
    conda run -n agentic-graphrag python tests/test_generator.py \
        --seed metabolism --out tests/test_sets/metabolism/

Output: tests/test_sets/<graph_id>/{structural,unanswerable}_tests.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import uuid
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Literal

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import real_ladybug as lb
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

from engine import compute_structural_index, get_embeddings_model
from models import SST_EDGE_TYPES, StructuralFacts
from tools import get_neighbours, find_paths


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class GroundTruth:
    required_nodes: list[str] = field(default_factory=list)
    required_trail: list[str] = field(default_factory=list)      # e.g. ["n_001 --LEADSTO--> n_003"]
    answer_must_contain: list[str] = field(default_factory=list)
    answer_must_not_contain: list[str] = field(default_factory=list)
    expected_gap_contains: str = ""   # concept text that should appear in gap inventory
    answerable: bool = True
    difficulty: Literal["single_hop", "multi_hop", "bridge", "domain_survey"] = "multi_hop"
    notes: str = ""


@dataclass
class TestCase:
    id: str
    query: str
    query_type: Literal[
        "causal_forward", "causal_backward", "bridge",
        "detail_retrieval", "domain_survey", "structural_overview",
        "cross_domain", "unanswerable_absent", "unanswerable_partial",
    ]
    authored_by: Literal["structural_generator", "unanswerable_generator", "ai_curated"]
    graph_id: str
    source_node: str
    ground_truth: GroundTruth = field(default_factory=GroundTruth)


def _tc_to_dict(tc: TestCase) -> dict:
    d = asdict(tc)
    return d


def save_test_cases(cases: list[TestCase], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump([_tc_to_dict(c) for c in cases], f, indent=2)
    print(f"  Saved {len(cases)} test cases → {path}")


def load_test_cases(path: Path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# LLM helpers
# ---------------------------------------------------------------------------

def _fast_llm() -> ChatOpenAI:
    return ChatOpenAI(
        model=os.environ.get("FAST_MODEL", "google/gemini-3.1-flash-lite-preview"),
        temperature=0.7,
        max_tokens=400,
        api_key=os.environ["OPENROUTER_API_KEY"],
        base_url="https://openrouter.ai/api/v1",
    )


_QUERY_SYSTEM = """\
You generate natural language question variants for a knowledge graph test suite.
You receive a template type, a subject concept, and optional context.
Generate exactly 3 different natural language questions that all ask the same thing.
Vary phrasing only — not meaning. Each question should sound like something a real user would ask.
Do not include the answer. Do not reference graph structure, node IDs, or edge types.
Return ONLY a JSON array of 3 strings.
"""


def _generate_query_variants(llm: ChatOpenAI, template: str, subject: str, context: str = "") -> list[str]:
    """Generate 3 natural language phrasings for a given structural template."""
    prompt = (
        f"Template: {template}\n"
        f"Subject: {subject}\n"
    )
    if context:
        prompt += f"Context: {context}\n"
    try:
        resp = llm.invoke([
            SystemMessage(content=_QUERY_SYSTEM),
            HumanMessage(content=prompt),
        ])
        text = (resp.content if hasattr(resp, "content") else str(resp)).strip()
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        variants = json.loads(text)
        if isinstance(variants, list) and len(variants) >= 1:
            return [str(v) for v in variants[:3]]
    except Exception as e:
        print(f"    Warning: query variant generation failed ({e}). Using template fallback.")
    # Fallback — simple template-based query
    fallback_map = {
        "causal_forward": f"What does {subject} lead to?",
        "causal_backward": f"What causes {subject}?",
        "bridge": f"How are the concepts in {subject} connected?",
        "detail_retrieval": f"What is {subject}?",
        "domain_survey": f"What are the components of {subject}?",
        "structural_overview": f"What are the most important concepts in this graph?",
        "unanswerable_absent": f"What is the role of {subject}?",
        "unanswerable_partial": f"What happens after {subject}?",
    }
    return [fallback_map.get(template, f"Tell me about {subject}.")]


_ABSENT_CONCEPT_SYSTEM = """\
You generate concept names that are plausibly related to a domain but are NOT present in the given graph.
These will be used as unanswerable test queries — the system should report a gap, not confabulate.
Return ONLY a JSON array of concept label strings (10-15 items).
Make them specific enough that a system with partial domain knowledge might be tempted to answer.
"""


def _generate_adjacent_absent_concepts(llm: ChatOpenAI, domain: str, existing_labels: list[str]) -> list[str]:
    """Generate concepts plausibly related to the domain but absent from the graph."""
    existing_str = ", ".join(existing_labels[:20])
    prompt = (
        f"Domain: {domain}\n"
        f"Concepts already in the graph: {existing_str}\n"
        "Generate 12 concepts that are plausibly related to this domain but are NOT in the list above."
    )
    try:
        resp = llm.invoke([
            SystemMessage(content=_ABSENT_CONCEPT_SYSTEM),
            HumanMessage(content=prompt),
        ])
        text = (resp.content if hasattr(resp, "content") else str(resp)).strip()
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        concepts = json.loads(text)
        if isinstance(concepts, list):
            return [str(c) for c in concepts]
    except Exception as e:
        print(f"    Warning: absent concept generation failed ({e}).")
    return []


# ---------------------------------------------------------------------------
# Graph reading helpers
# ---------------------------------------------------------------------------

def _all_nodes(conn: lb.Connection) -> list[dict]:
    rows = list(conn.execute(
        "MATCH (c:Concept) RETURN c.id, c.label, c.semantic_anchor, c.is_metanode"
    ))
    return [{"id": r[0], "label": r[1], "anchor": r[2] or "", "is_metanode": r[3]} for r in rows]


def _label_map(conn: lb.Connection) -> dict[str, str]:
    return {n["id"]: n["label"] for n in _all_nodes(conn)}


def _traverse_chain(
    conn: lb.Connection,
    start_id: str,
    direction: Literal["forward", "backward"],
    sst_type: str,
    max_depth: int = 4,
) -> list[str]:
    """BFS chain walk — returns ordered list of node IDs (including start)."""
    visited = [start_id]
    current = start_id
    for _ in range(max_depth):
        nbs = get_neighbours(conn, current, sst_type, direction)
        if not nbs:
            break
        # Follow the first unvisited neighbour
        next_node = next((nb["id"] for nb in nbs if nb["id"] not in visited), None)
        if not next_node:
            break
        visited.append(next_node)
        current = next_node
    return visited


def _get_contains_subtree(conn: lb.Connection, root_id: str) -> list[str]:
    """BFS over CONTAINS edges forward from root."""
    visited = [root_id]
    queue = [root_id]
    while queue:
        current = queue.pop(0)
        children = get_neighbours(conn, current, "contains", "forward")
        for child in children:
            if child["id"] not in visited:
                visited.append(child["id"])
                queue.append(child["id"])
    return visited


def _format_trail(node_ids: list[str], labels: dict[str, str], sst_type: str = "LEADSTO") -> list[str]:
    trail = []
    for i in range(len(node_ids) - 1):
        trail.append(f"{labels.get(node_ids[i], node_ids[i])} --{sst_type}--> {labels.get(node_ids[i+1], node_ids[i+1])}")
    return trail


def _concept_in_graph(conn: lb.Connection, concept: str) -> bool:
    """Check if a concept label appears anywhere in the graph (case-insensitive substring match)."""
    concept_lower = concept.lower()
    rows = list(conn.execute(
        "MATCH (c:Concept) RETURN c.label, c.semantic_anchor, c.text_content"
    ))
    for r in rows:
        label, anchor, content = (r[0] or "").lower(), (r[1] or "").lower(), (r[2] or "").lower()
        if concept_lower in label or concept_lower in anchor[:200]:
            return True
    return False


# ---------------------------------------------------------------------------
# Structural test generator
# ---------------------------------------------------------------------------

class StructuralTestGenerator:
    """Generates test cases by walking graph topology. Ground truth is structural."""

    def __init__(self, conn: lb.Connection, structural_index: dict[str, StructuralFacts], graph_id: str):
        self.conn = conn
        self.si = structural_index
        self.graph_id = graph_id
        self.labels = _label_map(conn)
        self._llm: ChatOpenAI | None = None

    def _get_llm(self) -> ChatOpenAI:
        if self._llm is None:
            self._llm = _fast_llm()
        return self._llm

    def _node_anchor_words(self, node_id: str) -> list[str]:
        """Extract a few key terms from a node's anchor for must_contain hints."""
        rows = list(self.conn.execute(
            "MATCH (c:Concept {id: $id}) RETURN c.semantic_anchor, c.label",
            {"id": node_id},
        ))
        if not rows:
            return []
        anchor, label = rows[0][0] or "", rows[0][1] or ""
        # Return the label words as must_contain hints (conservative)
        return [w for w in label.split() if len(w) > 4]

    def generate_causal_forward(self) -> list[TestCase]:
        cases: list[TestCase] = []
        origins = [nid for nid, f in self.si.items()
                   if "causal_origin" in f.roles or "causal_nexus" in f.roles]
        for node_id in origins:
            chain = _traverse_chain(self.conn, node_id, "forward", "leadsto", max_depth=4)
            if len(chain) < 2:
                continue
            label = self.labels.get(node_id, node_id)
            terminal_label = self.labels.get(chain[-1], chain[-1])
            variants = _generate_query_variants(
                self._get_llm(), "causal_forward", label,
                context=f"The chain ends at: {terminal_label}"
            )
            trail = _format_trail(chain, self.labels, "LEADSTO")
            must_contain = self._node_anchor_words(chain[-1])[:2]
            for q in variants:
                cases.append(TestCase(
                    id=f"sf_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="causal_forward",
                    authored_by="structural_generator",
                    graph_id=self.graph_id,
                    source_node=node_id,
                    ground_truth=GroundTruth(
                        required_nodes=chain,
                        required_trail=trail,
                        answer_must_contain=must_contain,
                        answerable=True,
                        difficulty="multi_hop" if len(chain) > 2 else "single_hop",
                        notes=f"Causal chain of length {len(chain)} from {label}",
                    ),
                ))
        return cases

    def generate_causal_backward(self) -> list[TestCase]:
        cases: list[TestCase] = []
        terminals = [nid for nid, f in self.si.items()
                     if "causal_terminal" in f.roles]
        for node_id in terminals:
            chain = _traverse_chain(self.conn, node_id, "backward", "leadsto", max_depth=4)
            if len(chain) < 2:
                continue
            label = self.labels.get(node_id, node_id)
            variants = _generate_query_variants(
                self._get_llm(), "causal_backward", label,
            )
            # Reverse chain so it reads cause → effect
            chain_rev = list(reversed(chain))
            trail = _format_trail(chain_rev, self.labels, "LEADSTO")
            must_contain = self._node_anchor_words(chain[-1])[:2]
            for q in variants:
                cases.append(TestCase(
                    id=f"sb_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="causal_backward",
                    authored_by="structural_generator",
                    graph_id=self.graph_id,
                    source_node=node_id,
                    ground_truth=GroundTruth(
                        required_nodes=chain_rev,
                        required_trail=trail,
                        answer_must_contain=must_contain,
                        answerable=True,
                        difficulty="multi_hop" if len(chain) > 2 else "single_hop",
                        notes=f"Backward chain from terminal {label}",
                    ),
                ))
        return cases

    def generate_bridge(self) -> list[TestCase]:
        """Find pairs of causal_origin nodes and check for paths between them."""
        cases: list[TestCase] = []
        bridges = [nid for nid, f in self.si.items()
                   if "inter_region_bridge" in f.roles]
        origins = [nid for nid, f in self.si.items()
                   if "causal_origin" in f.roles]

        # For each bridge node: try to find a path from any origin to it
        for bridge_id in bridges[:3]:  # cap at 3 bridge queries
            bridge_label = self.labels.get(bridge_id, bridge_id)
            if not origins:
                continue
            src_id = origins[0]
            src_label = self.labels.get(src_id, src_id)
            paths = find_paths(self.conn, src_id, bridge_id, max_hops=5)
            if not paths:
                continue
            best = paths[0]
            node_chain = best.get("node_chain", [src_id, bridge_id])
            edge_chain = best.get("edge_chain", [])
            trail = []
            for i in range(len(node_chain) - 1):
                etype = edge_chain[i].upper() if i < len(edge_chain) else "?"
                trail.append(
                    f"{self.labels.get(node_chain[i], node_chain[i])} --{etype}--> "
                    f"{self.labels.get(node_chain[i+1], node_chain[i+1])}"
                )
            variants = _generate_query_variants(
                self._get_llm(), "bridge",
                f"{src_label} and {bridge_label}",
                context="Find the connection between these two concepts",
            )
            must_contain = (
                self._node_anchor_words(bridge_id)[:1]
                + self._node_anchor_words(src_id)[:1]
            )
            for q in variants:
                cases.append(TestCase(
                    id=f"sbr_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="bridge",
                    authored_by="structural_generator",
                    graph_id=self.graph_id,
                    source_node=bridge_id,
                    ground_truth=GroundTruth(
                        required_nodes=node_chain,
                        required_trail=trail,
                        answer_must_contain=must_contain,
                        answerable=True,
                        difficulty="bridge",
                        notes=f"Bridge path via {bridge_label}",
                    ),
                ))
        return cases

    def generate_detail_retrieval(self) -> list[TestCase]:
        """Pick leaf/terminal nodes — query requires their specific content."""
        cases: list[TestCase] = []
        leaves = [
            nid for nid, f in self.si.items()
            if "causal_terminal" in f.roles or
               (f.out_degree.get("leadsto", 0) == 0 and f.in_degree.get("leadsto", 0) > 0)
        ]
        for node_id in leaves[:8]:  # cap at 8
            label = self.labels.get(node_id, node_id)
            variants = _generate_query_variants(
                self._get_llm(), "detail_retrieval", label,
            )
            must_contain = self._node_anchor_words(node_id)[:3]
            for q in variants:
                cases.append(TestCase(
                    id=f"sd_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="detail_retrieval",
                    authored_by="structural_generator",
                    graph_id=self.graph_id,
                    source_node=node_id,
                    ground_truth=GroundTruth(
                        required_nodes=[node_id],
                        answer_must_contain=must_contain,
                        answerable=True,
                        difficulty="single_hop",
                        notes=f"Detail retrieval for leaf {label}",
                    ),
                ))
        return cases

    def generate_domain_survey(self) -> list[TestCase]:
        """Pick containment roots — query requires the subtree."""
        cases: list[TestCase] = []
        # Nodes with CONTAINS out-edges and no CONTAINS in-edges
        nodes_with_contains_out = set()
        nodes_with_contains_in = set()
        for nid, f in self.si.items():
            if f.out_degree.get("contains", 0) > 0:
                nodes_with_contains_out.add(nid)
            if f.in_degree.get("contains", 0) > 0:
                nodes_with_contains_in.add(nid)
        roots = nodes_with_contains_out - nodes_with_contains_in
        for root_id in list(roots)[:3]:
            label = self.labels.get(root_id, root_id)
            subtree = _get_contains_subtree(self.conn, root_id)
            if len(subtree) < 2:
                continue
            variants = _generate_query_variants(
                self._get_llm(), "domain_survey", label,
            )
            must_contain = self._node_anchor_words(root_id)[:2]
            for q in variants:
                cases.append(TestCase(
                    id=f"sds_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="domain_survey",
                    authored_by="structural_generator",
                    graph_id=self.graph_id,
                    source_node=root_id,
                    ground_truth=GroundTruth(
                        required_nodes=subtree,
                        answerable=True,
                        difficulty="domain_survey",
                        notes=f"Domain survey from root {label}, {len(subtree)} nodes",
                    ),
                ))
        return cases

    def generate_structural_overview(self) -> list[TestCase]:
        """Overview query — requires landmark nodes (top by betweenness)."""
        ranked = sorted(
            self.si.items(),
            key=lambda x: x[1].betweenness_centrality,
            reverse=True,
        )
        top_ids = [nid for nid, _ in ranked[:4] if ranked[0][1].betweenness_centrality > 0]
        if not top_ids:
            return []
        graph_id_label = self.graph_id.replace("_", " ").title()
        variants = _generate_query_variants(
            self._get_llm(), "structural_overview",
            graph_id_label,
            context="Ask for an overview or summary of the main concepts",
        )
        must_contain = []
        for nid in top_ids[:2]:
            must_contain += self._node_anchor_words(nid)[:1]
        cases = []
        for q in variants[:1]:  # Only 1 variant for overview
            cases.append(TestCase(
                id=f"sov_{uuid.uuid4().hex[:8]}",
                query=q,
                query_type="structural_overview",
                authored_by="structural_generator",
                graph_id=self.graph_id,
                source_node=top_ids[0],
                ground_truth=GroundTruth(
                    required_nodes=top_ids,
                    answer_must_contain=must_contain,
                    answerable=True,
                    difficulty="domain_survey",
                    notes=f"Overview — requires top {len(top_ids)} landmark nodes",
                ),
            ))
        return cases

    def generate_all(self) -> list[TestCase]:
        cases: list[TestCase] = []
        print("  Generating causal_forward cases...")
        cases += self.generate_causal_forward()
        print("  Generating causal_backward cases...")
        cases += self.generate_causal_backward()
        print("  Generating bridge cases...")
        cases += self.generate_bridge()
        print("  Generating detail_retrieval cases...")
        cases += self.generate_detail_retrieval()
        print("  Generating domain_survey cases...")
        cases += self.generate_domain_survey()
        print("  Generating structural_overview cases...")
        cases += self.generate_structural_overview()
        print(f"  Structural generator: {len(cases)} total cases.")
        return cases


# ---------------------------------------------------------------------------
# Unanswerable test generator
# ---------------------------------------------------------------------------

class UnanswerableGenerator:
    """Generates queries the graph structurally cannot answer."""

    def __init__(self, conn: lb.Connection, structural_index: dict[str, StructuralFacts], graph_id: str):
        self.conn = conn
        self.si = structural_index
        self.graph_id = graph_id
        self.labels = _label_map(conn)
        self._llm: ChatOpenAI | None = None

    def _get_llm(self) -> ChatOpenAI:
        if self._llm is None:
            self._llm = _fast_llm()
        return self._llm

    def generate_absent_concepts(self, domain: str, count: int = 8) -> list[TestCase]:
        """Generate queries for concepts plausibly in the domain but absent from the graph."""
        existing_labels = list(self.labels.values())
        candidates = _generate_adjacent_absent_concepts(
            self._get_llm(), domain, existing_labels
        )
        # Confirm absence
        confirmed_absent = [c for c in candidates if not _concept_in_graph(self.conn, c)]
        cases = []
        for concept in confirmed_absent[:count]:
            # Generate a simple query for each absent concept
            variants = _generate_query_variants(
                self._get_llm(), "unanswerable_absent", concept,
                context=f"Domain: {domain}",
            )
            for q in variants[:1]:  # 1 variant per absent concept
                cases.append(TestCase(
                    id=f"ua_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="unanswerable_absent",
                    authored_by="unanswerable_generator",
                    graph_id=self.graph_id,
                    source_node="",
                    ground_truth=GroundTruth(
                        required_nodes=[],
                        answerable=False,
                        expected_gap_contains=concept,
                        answer_must_not_contain=[concept.lower()],
                        notes=f"Absent concept: '{concept}' — confirmed not in graph",
                    ),
                ))
        return cases

    def generate_partial_knowledge(self) -> list[TestCase]:
        """Generate queries about aspects structurally absent even though the domain is present.

        Two patterns:
        1. Causal nexus with no EXPRESSES edges → query about its attributes/properties
        2. Causal chain terminal → query about what comes after
        """
        cases = []

        # Pattern 1: causal_nexus with no EXPRESSES out-edges
        for nid, f in self.si.items():
            if "causal_nexus" in f.roles and f.out_degree.get("expresses", 0) == 0:
                label = self.labels.get(nid, nid)
                q = f"What are the specific measurable indicators or attributes of {label}?"
                cases.append(TestCase(
                    id=f"up_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="unanswerable_partial",
                    authored_by="unanswerable_generator",
                    graph_id=self.graph_id,
                    source_node=nid,
                    ground_truth=GroundTruth(
                        required_nodes=[nid],
                        answerable=False,
                        expected_gap_contains="measurable indicators",
                        notes=f"{label} is a causal_nexus with no EXPRESSES edges — attributes not modelled",
                    ),
                ))

        # Pattern 2: causal_terminal with forward LEADSTO out-degree == 0 → what comes next?
        for nid, f in self.si.items():
            if "causal_terminal" in f.roles and f.out_degree.get("leadsto", 0) == 0:
                label = self.labels.get(nid, nid)
                q = f"What are the downstream consequences or treatments for {label}?"
                cases.append(TestCase(
                    id=f"up_{uuid.uuid4().hex[:8]}",
                    query=q,
                    query_type="unanswerable_partial",
                    authored_by="unanswerable_generator",
                    graph_id=self.graph_id,
                    source_node=nid,
                    ground_truth=GroundTruth(
                        required_nodes=[nid],
                        answerable=False,
                        expected_gap_contains="downstream",
                        notes=f"{label} is a causal_terminal — no outgoing LEADSTO edges model what comes next",
                    ),
                ))
        return cases[:10]  # cap

    def generate_all(self, domain: str) -> list[TestCase]:
        cases = []
        print(f"  Generating absent_concept cases for domain '{domain}'...")
        cases += self.generate_absent_concepts(domain)
        print("  Generating partial_knowledge cases...")
        cases += self.generate_partial_knowledge()
        print(f"  Unanswerable generator: {len(cases)} total cases.")
        return cases


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _detect_domain(conn: lb.Connection) -> str:
    """Infer a short domain description from the graph's node labels."""
    rows = list(conn.execute("MATCH (c:Concept) RETURN c.label LIMIT 5"))
    labels = [r[0] for r in rows]
    return ", ".join(labels[:3])


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SST test cases from a graph")
    parser.add_argument("--seed", default="metabolism",
                        help="Seed profile name (metabolism, auth_service, memory_cognition, ...)")
    parser.add_argument("--db", default=None,
                        help="Path to existing .lbug file (if not using seed)")
    parser.add_argument("--domain", default="",
                        help="Short domain description for unanswerable generation")
    parser.add_argument("--out", default="tests/test_sets",
                        help="Output directory for test case JSON files")
    args = parser.parse_args()

    from dotenv import load_dotenv
    load_dotenv()

    if args.db:
        from pathlib import Path as P
        database = lb.Database(args.db)
        conn = lb.Connection(database)
        graph_id = P(args.db).stem
    else:
        from tests.fixture_db import create_fixture_db
        import tempfile
        tmp = tempfile.mkdtemp()
        db_path = Path(tmp) / f"{args.seed}.lbug"
        print(f"Creating fixture DB from seed '{args.seed}'...")
        conn = create_fixture_db(args.seed, db_path)
        graph_id = args.seed

    print("Computing structural index...")
    si = compute_structural_index(conn)

    out_dir = Path(args.out) / graph_id
    domain = args.domain or _detect_domain(conn)

    print(f"\n--- Structural generator (graph_id={graph_id}) ---")
    struct_gen = StructuralTestGenerator(conn, si, graph_id)
    structural_cases = struct_gen.generate_all()
    save_test_cases(structural_cases, out_dir / "structural_tests.json")

    print(f"\n--- Unanswerable generator (domain={domain!r}) ---")
    unans_gen = UnanswerableGenerator(conn, si, graph_id)
    unanswerable_cases = unans_gen.generate_all(domain)
    save_test_cases(unanswerable_cases, out_dir / "unanswerable_tests.json")

    print(f"\nDone. Total: {len(structural_cases)} structural, {len(unanswerable_cases)} unanswerable.")
    print(f"Output: {out_dir}/")


if __name__ == "__main__":
    main()
