"""Project bootstrap — ``init`` (backlog P3). Time-to-first-orient under 15 min.

One command lays down a runnable project: a generated token, a `.env` wired to
the graph/store/account paths, an empty workbook area, an account, and a
NEXT_STEPS walkthrough. It does not author a construction program; the agent
writes ``workbook/build.py`` in its own session. ``--demo`` copies a ready graph
so ``orient`` works immediately.

Deterministic, no LLM. Run:
    python -m mcp_server.bootstrap init ./my-project [--demo]
"""

from __future__ import annotations

import json
import secrets
import shutil
import sys
from pathlib import Path
from typing import Any


def _env_template(db: Path, store: Path, token: str, account_dir: Path) -> str:
    return (
        "# Graphauthor project — generated by `init`. Set OPENROUTER_API_KEY (or manage it\n"
        "# via the settings surface: POST /operator/settings/key).\n"
        f"SST_DB_PATH={db}\n"
        f"SST_MCP_STORE_PATH={store}\n"
        f"SST_MCP_TOKEN={token}\n"
        f"SST_MCP_ACCOUNT_PATH={account_dir}\n"
        "SST_AUTO_SEED=0\n"
        "OPENROUTER_API_KEY=\n"
    )


def _next_steps(demo_ready: bool, db: Path) -> str:
    build = (
        "3. Prepare a workbook, then ask your agent to write workbook/build.py:\n"
        "     python path/to/repo/scripts/workbook.py prepare \\\n"
        "       --workbook workbook --source sources/your-document.html\n"
        "   Run build.py, then validate and materialize its encoding:\n"
        "     python path/to/repo/scripts/workbook.py materialize \\\n"
        f"       --workbook workbook --encoding workbook/out/encoding.json --out {db.name}\n"
        if not demo_ready else
        "3. A demo graph is already in place — skip to orient, or replace it with your own:\n"
        "     python path/to/repo/scripts/workbook.py prepare --workbook workbook --source sources/your.md\n"
    )
    return (
        "# Next steps\n\n"
        "1. Add your OpenRouter key: edit `.env` (OPENROUTER_API_KEY=…) or, once the\n"
        "   server is up, `POST /operator/settings/key`.\n"
        "2. Load the env: `set -a; source .env; set +a`\n"
        f"{build}"
        "4. Start the server:\n"
        "     conda run -n agentic-graphrag python -m mcp_server.http\n"
        "5. Orient — ask the MCP `orient` tool (or GET the map). You should see your graph.\n\n"
        "The workbook is an open programming surface: build.py may use the supplied\n"
        "parsers, its own parsing code, or other permitted libraries. The host only\n"
        "validates and materializes its encoding.\n"
    )


def _lay_demo_graph(db: Path) -> bool:
    """Copy a ready fixture graph (+ sidecars) to ``db`` so orient works at once.
    Best-effort: returns False if no fixture is available."""
    try:
        from mcp_server.fixture import ensure_fixture
        src = Path(ensure_fixture("runtime/hexagonal_orders.lbug"))
    except Exception:
        return False
    if not src.exists():
        return False
    shutil.copy2(src, db)
    # copy known sidecars if present (best-effort; the engine regenerates .idx)
    for sc_src, sc_dst in ((Path(str(src) + ".idx"), Path(str(db) + ".idx")),
                           (src.with_suffix(".grain.json"), db.with_suffix(".grain.json"))):
        if sc_src.exists():
            shutil.copy2(sc_src, sc_dst)
    return True


def init_project(project_dir: Path | str, *,
                 token: str | None = None, actor: str = "operator",
                 demo: bool = False) -> dict[str, Any]:
    """Scaffold a runnable project. Returns a manifest of what was created."""
    from mcp_server.account import Account

    project_dir = Path(project_dir)
    project_dir.mkdir(parents=True, exist_ok=True)
    token = token or secrets.token_urlsafe(32)
    (project_dir / "sources").mkdir(exist_ok=True)
    (project_dir / "workbook").mkdir(exist_ok=True)

    account_dir = project_dir / "account"
    Account(account_dir).set_actor(actor)

    db = project_dir / "graph.lbug"
    store = project_dir / "graph.writestore.sqlite"
    (project_dir / ".env").write_text(_env_template(db, store, token, account_dir))

    demo_ready = _lay_demo_graph(db) if demo else False
    (project_dir / "NEXT_STEPS.md").write_text(_next_steps(demo_ready, db))

    return {
        "project_dir": str(project_dir), "token": token,
        "db_path": str(db), "store_path": str(store), "account_path": str(account_dir),
        "demo_graph": demo_ready,
        "created": ["sources/", "workbook/", ".env", "NEXT_STEPS.md", "account/"]
                   + (["graph.lbug"] if demo_ready else []),
    }


def main(argv: list[str] | None = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog="graphauthor", description="Graphauthor project bootstrap")
    sub = ap.add_subparsers(dest="cmd")
    p = sub.add_parser("init", help="scaffold a new project")
    p.add_argument("project_dir")
    p.add_argument("--actor", default="operator")
    p.add_argument("--demo", action="store_true", help="lay down a demo graph so orient works now")
    args = ap.parse_args(argv)
    if args.cmd != "init":
        ap.print_help()
        return 2
    manifest = init_project(args.project_dir, actor=args.actor, demo=args.demo)
    # never print the token to stdout logs beyond the manifest the operator asked for
    print(json.dumps(manifest, indent=2))
    print(f"\n→ {args.project_dir}/NEXT_STEPS.md", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
